import React from "react";
import {Logo} from "../components/Logo";
import { Navbar } from "../components/Navbar";
import { VideoHome } from "../components/VideoHome";
import "./HomePage.css";


export default function HomePage(){
    return(
        <>
            <Logo/>
            <Navbar/>
            <VideoHome/>
            <div className="content">
                <p>This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                </p>
            </div>
        </>
    );
}