import { Inter } from "next/font/google";
import "../globals.css";
import { MiniLogo } from "../../components/MiniLogo";
import Footer from "../../components/Footer";
import { NextIntlClientProvider } from "next-intl"
import { getMessages } from 'next-intl/server';
import { ReactNode } from "react";
import { Menu } from "../../components/Menu";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Baja ÉTS",
  description: "Generated by the baja blasters",
  icon: "/favicon.ico"
};

type TRootLayoutProps = {
  children: ReactNode;
  params: {
    locale: string
  }
}

export default async function RootLayout(props: TRootLayoutProps) {

  const { children, params } = props

  const { locale } = params

  const messages = await getMessages();

  return (
    <html lang={locale} className="bg-black m-0 p-0 h-full overflow-hidden text-white no-scrollbar">
      <body className={clsx(inter.className, 'bg-black m-0 p-0 h-full text-white')}>
        <NextIntlClientProvider messages={messages}>
          <MiniLogo />
          <Menu />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
