import {Logo} from "./components/Logo";
import {VideoHome} from "./components/VideoHome";
import 'HomePage.css';

export default function HomePage(){
    return(
        <>
            <Logo/>
            <VideoHome/>
            <div className="content">
                <p>This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                This is a paragraph that appears after the video.
                </p>
            </div>
        </>
    );
};