"use client";
import React from "react";
import HomePage from "./pages/HomePage";
import "./Page.css";


export default function Page() {
  return (
    <>
      <HomePage/>
      <div className="content">
        <p>This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        </p>
      </div>
    </>
  );
}
