"use client";
import React from "react";
import {Navbar} from "./components/Navbar";
import {VideoHome} from "./components/VideoHome";
import "./page.css";
import {Logo} from'./components/Logo'


export default function Home() {
  return (
    <>
      <Logo/>
      <Navbar/>
      <VideoHome/>
      <div className="content">
        <p>This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        This is a paragraph that appears after the video.
        </p>
      </div>
    </>
  );
}
