import { Metadata } from "next"
import { ReactNode } from "react"

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

type TRootLayoutProps = {
  children: ReactNode
}

export default function RootLayout(props: TRootLayoutProps) {

  const { children } = props

  return (
    <html lang="en">
      <body className="text-white h-full m-0 bg-black">
        {children}
      </body>
    </html>
  )
}
